# Generated by Django 4.0.4 on 2022-08-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100, verbose_name='Produto')),
                ('estilo', models.CharField(max_length=100, verbose_name='Estilo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
            ],
        ),
    ]
